<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Nota_m extends CI_Model
{

    public $table = 'tbl_nota';
    public $id = 'id_nota';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_nota', $q);
	$this->db->or_like('nomor', $q);
	$this->db->or_like('penerimanota', $q);
	$this->db->or_like('namateknisi', $q);
	$this->db->or_like('namapegawai', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('totalbiaya', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('isservice', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_nota', $q);
	$this->db->or_like('nomor', $q);
	$this->db->or_like('penerimanota', $q);
	$this->db->or_like('namateknisi', $q);
	$this->db->or_like('namapegawai', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('totalbiaya', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('isservice', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getnomornota(){
        $this->db->select("id_nota");
        $this->db->from("tbl_nota");
        $this->db->limit(1);
        $this->db->order_by('id_nota',"DESC");
        $query = $this->db->get();
        if($query->num_rows() > 0){
        $category['rows'] = $query->num_rows();
        return $query->row();

            }
            else {
        return $query->row();

            }
        // $query = $this->db->get();
        // $result = $query->result();

        // $last_row = $this->db->select('id_nota')->order_by('id_nota',"desc")->limit(1)->get('tbl_nota')->row();
        //echo $last_row->id_nota;
    }

    function createNota($table,$data){
        $query = $this->db->insert($table, $data);
        return $this->db->insert_id();// return last insert id
    }

    function insertNotadata($table, $data){
        $this->db->insert($table, $data);
    }

    function getnamapegserv($table){
        $this->db->order_by('id_peg_service', 'DESC');
        return $this->db->get_where($table, "ispeg = 0")->result();
    }

    function deleteND($table, $id)
    {
        $this->db->where('id_notadata', $id);
        $this->db->delete($table);
    }
}

/* End of file Nota_m.php */
/* Location: ./application/models/Nota_m.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-04 07:17:11 */
/* http://harviacode.com */